name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install tools
      run: sudo apt-get install -y make upx

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install Go Utils
      run: go install github.com/google/go-licenses@latest

    - name: Build
      run: sh dist.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ github.token }}
